version: '3.3'

networks:
  gui-to-www:
    driver: "bridge"
    
services:
  RStudio:
    image: rocker/rstudio
    environment:
      PASSWORD: "super_secure_pw"
    ports:
      - "8787:8787"
    networks: 
      - gui-to-www
    
  microservices-gui:
    build: ./microservices-gui
    depends_on:
      - RStudio
    volumes:
      - ${XSRV}
    environment:
      DISPLAY: ${DISPLAY_IP}
      BROWSER: "firefox"
    networks: 
      - gui-to-www
      