version: '3.8'

networks:
  gui-to-www:
    driver: "bridge"
    
services:
  RStudio:
    image: rocker/rstudio
    environment:
      PASSWORD: "super_secure_pw"
    ports:
      - "8787:8787"
    networks: 
      - gui-to-www
      
  # SSH default port
  # my-browser:
    # build: 
      # context: ./firefox
      # args:
        # SSH_PASS: root
    # environment:
      # DISPLAY: "172.19.224.1:0.0"
      # BROWSER: "firefox"
    # networks:
      # - gui-to-www
    
  microservices-gui:
    build: ./microservices-gui
    depends_on:
      - RStudio
    environment:
      DISPLAY: ${DISPLAY_IP}
      BROWSER: "firefox"
    networks: 
      - gui-to-www
      